import os

seq_forward = ("TGGTGTCGTCGCTCGTAGTCGCTAGTAGTAGTCGTCGCTCGCTGATGCTGATCGTCGCGTCTGAGCTGTGTCGTCGTCGCTGTAGCTCGTAGCTGTAGCTAGTCGCTGTAGCTGCTGCGCCGCGTAGTGTGTGTAGTGCTGCTGCTAGTCGTAGCTCGTCGTAGCTGCTAGTCGCTGCTCGCTGATGCTCGTCGCTAGTCGCGTAGTCGTAGTCGCTGTCGTAGTCGTAGTCGTAGTCGTCGTCGTAGTCGTAGTCGGAGTTTAGTGAGAAACCGTTGCTGGGGAGCAGTGTTATTTTTATCCCCCCGTTTGTTTTCTTCGAGATAATCTATGTCCTCGTCTACTATGTCATAATCTTCTGTACACAAACGGTCCTTTTACCTTTGGTTTTTACTATCCTCCTTAACCTCCAAAATAATTTCACTCTGTCATACTCGTCTATGGGTATCTTTAGACACCTGTATTTCGATATCCATGTCATAATCATCCTGGATGTGGACAGTTGTAATAACCTTCTTTAAACAACTGAGTTTAACCAACGTGAAATTTAAAAGGGTAATCAGGATAACTTTGACATGGTCATTTTAATTTCGGTCCTTACCTACCGGGTTTTCAATTTGTTACCGGTAACTGTCTTCTTTTTTATTTTCGTAATTATCTTTAAACATGTCTTTACCTTTTCCTTCCCTTTTAAAGTTTTTAACCCGGACTTTTAGGTATGTTGTGAGGACATAAACGGTATTTCTTTTTCCTGTCATGATTTACCTCTTTTAATCATCTAAAGTCTCTTGAATTATTCTCTTGAGTTCTGAAGACCCTTCAAGTTAATCCTTATGGTGTGGGTCGTCCCAATTTTTTCTTTTTTAGTCATTGTCATGACCTACACCCACTACGTATAAAAAGTCAAGGTAACCTATTTCTGAAATCTTTCATATGACGTAAATGGTATGGGTCATATTTGTTACTCTGTGGTCCCTAATCCATAGTCATGTTACACGATGGTGTCCCTACCTTTCCTAGTGGTCGTTATAAGGTTTCATCGTACTGTTTTTAAAACCTCGGAAAATCTTTTGTTTTAGGTCTGTATCAATAGATAGTTATATACCTACTAAATATACATCCTAGACTGAATCTTTATCCCGTTGTATCTTGTTTTCATCTCCTTGACTCTGTTGTAGACAACTTCACCCCCAAATGATGTGGTCTGTTTTTTGTAGTCTTTCTTGGAGGTAAAGAAACCTACCCAATATCTGATCGTGTAGCTGATGCTCGTAGTCGTCGATGCTCGTGTCGTAGTCGATGCTGTAGCTGATCGATCGTACGCGCGTGTGTTTCCTAGCCCGCGATGCTAGTAGCTGTAGTGTGATGCTCGCTCGTAGCTGCTAGTCGGTACTAGCTAGCTAGCTGCTACGATCGATCGATCGACTAGCTACGATCGATCGATCGACTGACTAGCTACGATCGATCAGCTAGCTACGTACGATCGAT")
seq_reverse = ("TAGCTAGCATGCATCGATCGACTAGCTAGCATCGATCAGTCAGCTAGCTAGCTAGCATCGATCAGCTAGCTAGCTAGCATCGTCGATCGATCGATCATGGCTGATCGTCGATGCTCGCTCGTAGTGTGATGTCGATGATCGTAGCGCCCGATCCTTTGTGTGCGCGCATGCTAGCTAGTCGATGTCGTAGCTGATGCTGTGCTCGTAGCTGCTGATGCTCGTAGTCGATGTGCTAGTCT")

string = ('''
--------------------------------------------------------------------------------------------
                                         primerTest                                         
--------------------------------------------------------------------------------------------


   5'-TAGCGCATCAGCGATAGAGAGAATCGATCAGCTAACGCTAGCACAGCTACAGACTCAGTAGCGCACAGCATCAGCATCAG-3'
      ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
   3'-ATCGCGTAGTCGCTATCTCTCTTAGCTAGTCGATTGCGATCGTGTCGATGTCTGAGTCATCGCGTGTCGTAGTCGTAGTC-5'


   5'-TAGCGCATCAGCGATAGAGAGAATCGATCAGCTAACGCTAGCACAGCTACAGACTCAGTAGCGCACAGCATCAGCATCAG-3'
         |||||||||||||||||||
      5'-GCGTAGTCGCTATCTCTCT-3' --> primer 1

                                                primer 2 <-- 3-GTAGCGCACAGCATCAGCAT
                                                               ||||||||||||||||||||
   3'-ATCGCGTAGTCGCTATCTCTCTTAGCTAGTCGATTGCGATCGTGTCGATGTCTGAGTCATCGCGTGTCGTAGTCGTAGTC

--------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------

Crie os primer 1 (Forward) e primer 2 (Reverse) para a região em vermelho (interesse do estudo):

>arquivo|fasta|sempre|inicia|com|sinal|maior|que
ACCACAGCAGCGAGCATCAGCGATCATCATCAGCAGCGAGCGACTACGACTAGCAGCGCAGACTCGACACAGCAGCAGCG
ACATCGAGCATCGACATCGATCAGCGACATCGACGACGCGGCGCATCACACACATCACGACGACGATCAGCATCGAGCAG
CATCGACGATCAGCGACGAGCGACTACGAGCAGCGATCAGCGCATCAGCATCAGCGACAGCATCAGCATCAGCATCAGCA
GCAGCATCAGCATCAGCCTCAAATCACTCTTTGGCAACGACCCCTCGTCACAATAAAAATAGGGGGGCAAACAAAAGAAG
CTCTATTAGATACAGGAGCAGATGATACAGTATTAGAAGACATGTGTTTGCCAGGAAAATGGAAACCAAAAATGATAGGA
GGAATTGGAGGTTTTATTAAAGTGAGACAGTATGAGCAGATACCCATAGAAATCTGTGGACATAAAGCTATAGGTACAGT
ATTAGTAGGACCTACACCTGTCAACATTATTGGAAGAAATTTGTTGACTCAAATTGGTTGCACTTTAAATTTTCCCATTA
GTCCTATTGAAACTGTACCAGTAAAATTAAAGCCAGGAATGGATGGCCCAAAAGTTAAACAATGGCCATTGACAGAAGAA
AAAATAAAAGCATTAATAGAAATTTGTACAGAAATGGAAAAGGAAGGGAAAATTTCAAAAATTGGGCCTGAAAATCCATA
CAACACTCCTGTATTTGCCATAAAGAAAAAGGACAGTACTAAATGGAGAAAATTAGTAGATTTCAGAGAACTTAATAAGA
GAACTCAAGACTTCTGGGAAGTTCAATTAGGAATACCACACCCAGCAGGGTTAAAAAAGAAAAAATCAGTAACAGTACTG
GATGTGGGTGATGCATATTTTTCAGTTCCATTGGATAAAGACTTTAGAAAGTATACTGCATTTACCATACCCAGTATAAA
CAATGAGACACCAGGGATTAGGTATCAGTACAATGTGCTACCACAGGGATGGAAAGGATCACCAGCAATATTCCAAAGTA
GCATGACAAAAATTTTGGAGCCTTTTAGAAAACAAAATCCAGACATAGTTATCTATCAATATATGGATGATTTATATGTA
GGATCTGACTTAGAAATAGGGCAACATAGAACAAAAGTAGAGGAACTGAGACAACATCTGTTGAAGTGGGGGTTTACTAC
ACCAGACAAAAAACATCAGAAAGAACCTCCATTTCTTTGGATGGGTTATAGACTAGCACATCGACTACGAGCATCAGCAG
CTACGAGCACAGCATCAGCTACGACATCGACTAGCTAGCATGCGCGCACACAAAGGATCGGGCGCTACGATCATCGACAT
CACACTACGAGCGAGCATCGACGATCAGCCATGATCGATCGATCGACGATGCTAGCTAGCTAGCTGATCGATGCTAGCTA
GCTAGCTGACTGATCGATGCTAGCTAGTCGATCGATGCATGCTAGCTA

''')

print(string)

flag=True
while flag:
    try:
        primer1 = input("Insira seu desenho do primer 1 (forward): ").upper()
        primer2 = input("Insira seu desenho do primer 2 (reverse): ").upper()
        primer3 = (seq_forward.find(primer1))
        primer4 = (seq_reverse.find(primer2))
        len_primer3 = len(primer1)
        len_primer4 = len(primer2)
        if primer3 != -1 and primer4 != -1 and len_primer3 >= 18 and len_primer4 >= 18 and len_primer3 < 28 and len_primer4 < 28:
            print('''
            Perfeito! O seu primer hibridiza perfeitamente com a SEQUÊNCIA!''')
            flag = False
        else:
            print('''

>> Certeza que está tudo certo?
>> Os primers podem estar muito curtos (> 18pb), muito longos (< 28pb) ou você digitou algo errado!
>> Tenta de novo! :)
            ''')
    except:
        flag = True